FROM node:16-alpine as base

RUN apk update && apk add --upgrade apk-tools && apk upgrade --available
RUN apk --no-cache add curl

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . .

ENV LISTEN_PORT=3000
EXPOSE $LISTEN_PORT

ENV NODE_ENV=development

CMD [ "yarn", "start:dev" ]
